# 226. What is an error object

- JavaScript의 Error 객체는 런타임 오류가 발생했을 때 생성되며, 오류에 대한 정보를 담고 있다.
- 개발자는 try catch 문으로 에러처리를 할 수 있다.

```js
new Error([message[, fileName[, lineNumber]]])
// 대괄호의 의미 알고 계신가요?
```

- 매개변수 없이: new Error()
- 메시지만 전달: new Error('오류발생')
- 메시지와 파일 이름 전달: new Error('오류발생', 'index.js')
- 메시지, 파일 이름, 줄 번호 모두 전달: new Error('오류발생', 'index.js', 2)
- 일반적으로, fileName과 lineNumber는 JavaScript 엔진이 오류를 생성할 때 자동으로 설정되며 브라우저에서는 지원되지 않는다.

```js
let age = 29;

try {
  if (age < 30) throw new Error('나이 더먹고 와라');
} catch (e) {
  console.log(e.name); // Error
  console.log(e.message); // 나이 더먹고 와라
}

let age = 29;

try {
  if (age < 30) throw new TypeError('나이 더먹고 와라');
} catch (e) {
  console.log(e.name); // TypeError
  console.log(e.message); // 나이 더먹고 와라
}

try {
  greeting('howoo');
} catch (err) {
  console.log(err.name); // ReferenceError
  console.log(err.message); // greeting is not defined
}
```

<img width="303" alt="image" src="https://github.com/CS-TeamStudy/CS_Study_for_Interview/assets/87072568/b267ac13-f1c0-4dd1-acd7-d872411da829">

# 227. When you get a syntax error

- 아래에서 다룸

# 228. What are the different error names from error object

- EvalError : eval() 함수 내부에서 발생한 에러

  - eval() 함수 : 문자열을 JavaScript 코드로 변환하여 실행하는 함수, 현대 자바스크립트에서는 eval() 함수 사용을 피하고 다른 방법을 사용하는 것이 좋다.

  ```js
  const x = 10;
  const y = 20;
  console.log(x + y); // 30
  console.log('x + y'); // ?
  console.log(eval('x + y')); // ?
  ```

```js
try {
  eval('a'); // a가 정의되지 않았기 때문에 오류 발생
} catch (error) {
  if (error instanceof EvalError) {
    console.log(error);
  } else {
    console.log(error); // ReferenceError: a is not defined
    // 현대자바스크립트에서는 EvalError는 eval()로로 치환된 자바스크립트에서 발생한 오류로 표시된다.
  }
}
```

- RangeError : 숫자값이 허용범위를 벗어난 경우 발생하는 오류

```js
try {
  const largeArray = new Array(10e9); // 매우 큰 배열을 생성하려는 시도
} catch (error) {
  if (error instanceof RangeError) {
    console.log(error); // RangeError: Invalid array length
  } else {
    console.log(error);
  }
}
```

- ReferenceError : 참조할 수 있는 값이 없는 경우 발생

```js
try {
  a; // a가 정의되지 않았기 때문에 오류 발생
} catch (error) {
  if (error instanceof ReferenceError) {
    console.log(error); // ReferenceError: a is not defined
  } else {
    console.log(error);
  }
}
```

- SyntaxError : 잘못된 문법을 사용한 경우 발생함

```js
try {
  console.log('Hello, World'; // ) 가 없다.
} catch (error) {
  if (error instanceof SyntaxError) {
    console.log(error);
  } else {
    console.log(error);
  }
}
```

- 위 예시의 에러는 catch로 잡을 수 없다.

<img width="300" alt="image" src="https://github.com/CS-TeamStudy/CS_Study_for_Interview/assets/87072568/7c92c0ed-0643-4c6c-8391-0ae6e3aad4a7">

```js
try {
  eval('console.log("Hello, World"');
} catch (error) {
  if (error instanceof SyntaxError) {
    console.log(error);
  } else {
    console.log(error);
  }
}
```

<img width="258" alt="image" src="https://github.com/CS-TeamStudy/CS_Study_for_Interview/assets/87072568/7e63efa9-c97b-47c6-bb08-60ecad9aa74e">

- TypeError : 타입이 부적절한 경우 발생하는 오류

```js
try {
  const x = 1;
  const y = x.toUpperCase();
} catch (error) {
  if (error instanceof TypeError) {
    console.log(error); // TypeError: x.toUpperCase is not a function
  } else {
    console.log(error);
  }
}
```

- URIError : URI관련 함수에서 발생하는 오류

* URI 관련 내용은 전에 다뤘음 [링크](<https://github.com/CS-TeamStudy/CS_Study_for_Interview/blob/master/Javascript/Object.create()%20%26%20encode%20URL%20%26%20decode%20URL.md>)

```js
try {
  const encodedURL = decodeURI('$$%$%');
} catch (error) {
  if (error instanceof URIError) {
    console.log(error); // URIError: URI malformed
  } else {
    console.log(error);
  }
}
```

# 229. What are the various statements in error handling

- try: 에러가 발생할 수 있는 코드 블록을 정의
- catch: try 블록에서 발생한 예외를 잡아내고 처리하는 데 사용
- throw: 명시적으로 예외를 발생시키는 데 사용된다. 개발자가 직접 커스텀 에러를 생성할 수 있다.
- finally: try 블록이나 catch 블록의 실행과 상관없이 항상 실행되는 코드 블록을 정의
